version: '3.8'

services:
  container-postgres:
    image: postgres
    container_name: container-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "senha"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432
    volumes:
     - ./data/postgres:/var/lib/postgresql/data

  container-pgadmin:
    image: dpage/pgadmin4
    container_name: container-pgadmin
    restart: always
    depends_on:
      - container-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8081:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  my_network:

volumes:
  pgdata:
