version: '3.8'

services:
  container-postgres:
    image: postgres:latest
    container_name: container-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "senha"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "mydb"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  container-pgadmin:
    image: dpage/pgadmin4
    container_name: container-pgadmin
    restart: always
    depends_on:
      - container-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
  pgadmindata:
