version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - store_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: store

phpmyadmin:
  image: phpmyadmin
  ports:
    - 8000:80


volumes:
  store_db: